### ISSUE TITLE
Add an option to actually disable image viewer on hover

### ISSUE THREAD

**Issue by Delgan** [Mr-VincentW/PhotoShow#1]
Hey!

This request may seem odd, I understand. :sweat_smile: 
I just discovered your extension, and it's a real gem! Many sites today obfuscate images, making it impossible to download them manually without inspecting the source code. Thank you for solving this problem!

So, I'm using PhotoShow exclusively to access the direct link of full-size images, through the contextual menu options. I don't really use the image viewer, most of the time I just need the link of the image to download or upload it somewhere else. 

I understand that the initial use case for PhotoShow is to show the HD images without any click, but do you think that an option to disable the mousehover preview could be added?

Anyway, I really like how well polished is you extension, keep up the good work! :+1:

**Comment by Delgan** [comment]
Well, actually I could just use a key-modifier for the activation mode and have best of both worlds. No extra work required. :smile:

**Comment by Mr-VincentW** [comment]
Hi Delgan,

Thank you for the feedback.

Yes, you may use ACTIVATION MODE control to avoid an annoying viewer popup. However, you reminded me of another specific use case in which only the full-size image links are needed. I'm considering to add a contextual menu option for copying the links to the system clipboard. It'll be done in PhotoShow's future updates.

Thanks a lot.

**Comment by Delgan** [comment]
Yeah, that would be awesome too! Thanks a lot to **you** for this great extension!

**Comment by Mr-VincentW** [comment]
Hi Delgan,

I've added a new contextual menu option to PhotoShow for copying HD image addresses in the 4.1.0.0 version. The corresponding hotkey is `C`. You may have a try after Google Webstore has completed reviewing and release the new version. As for Firefox Add-ons, it's already ready to use.

There are some tips that might be helpful. Firstly, all the hotkeys only work when the HD image is displayed or in its loading procedure (this limit may also be canceled in the future). Secondly, for some websites, when you press the hotkey `C` (or via contextual menu option) to copy the HD image address, you might not get it done immediately as parsing HD image addresses on these websites requires extra processes which may take considerably long time. After the whole procedure is successfully done, you will see a message on top of the page.

I hope this would be helpful.

Kind regards.

**Comment by Delgan** [comment]
Hey! That's great, thanks for the update, tips and explanations!

I noticed some changes / bugs, I'm not sure if this is related to the new version or an issue with my setup. :confused: 

So, I'm using PhotoShow 4.1 with Firefox 73 and I use the Shift activation key. However, it seems PhotoShow does not appear in the contextual menu until Shift is pressed and the full image displayed, is it expected? Then, if I chose "Open HD image in new tab" the contextual menu disappear (two others options are fine). Finally, the "Copy HD image address" does not seem to copy the link to clipboard, although Shift + C is working fine.

I recorded a `.gif` demonstrating this:
![Peek 2020-03-13 16-13](https://user-images.githubusercontent.com/4193924/76635932-831d2f00-6548-11ea-9597-6b7cfd77c4d8.gif)

I tried to restart Firefox and disable others add-ons without much success. It happens on several website (tested on Amazon / Instagram). 

If there is anything I can do to help you with this, please ask me!

**Comment by Mr-VincentW** [comment]
Hi Delgan,

Thanks a lot for your elaborate description of the issue and the awesome screen record! 

The problem you mentioned has been there for long, ever since PhotoShow started to support these hotkeys. It was designed to work only when the image viewer is displayed at first but soon I realized some hotkey actions need to work as well even if the viewer is hidden. It was in my TO-DO list, but as you mentioned it, I decided to fix it now.

Since version 4.1.2 PhotoShow has allowed users to trigger `Tab`, `S`, and `C` actions, regardless of the display of the image viewer. However, you might still occasionally find that the contextual menu items do not show at times. It's because PhotoShow needs time to check whether it can parse an image when you hover your mouse on it. Usually, this process is fast enough that users will have no perception. But there're still times that you are even faster! This issue is a tough one since as long as the contextual menu is displayed, I can not update it anymore. Thus it depends on whether PhotoShow can finish its checking before you right-click on the images. It seems that the only solution is "Do it again" now... 

I've also fixed the style issue of the global messages on Instagram. Thanks for your gif!

Enjoy your weekends!

**Comment by Delgan** [comment]
Yeah, that's awesome! Thanks a lot for this blazingly fast update! :tada: 

I better understand the process behind image parsing and contextual menu generated by PhotoShow. Your explanation will probably save me a few surprises.

Take care! :+1:
