### ISSUE TITLE
[Facebook] Some bugs on Facebook

### ISSUE THREAD

**Issue by antarn88** [Mr-VincentW/PhotoShow#106]
I found some Facebook bugs:

- Enlargement of opened/clicked photos are broken: If I open a large image, i.e. click on the photo, the preview window does not appear. Also there is no image type context menu in this case, typical: save image, copy image etc.

- Facebook story scrollbar is broken: scrolling bar on opened Facebook story list is does not work.    On this page:   https://www.facebook.com/stories
  I attached a screenshot.
  
![scrolling](https://user-images.githubusercontent.com/61657422/223515613-8ee0d0c5-7c91-4818-97a3-dae674bdffcc.png)

 

Please check these bugs!

I use Google Chrome v110 on Windows 11, and PhotoShow 4.20.1 (Feb 19, 2023)

**Comment by Mr-VincentW** [comment]
Thanks mate I've been working on them. The second issue has been fixed and will be published with the next update. The first one will be addressed later as well.

**Comment by Mr-VincentW** [comment]
Thank you for your feedback. Both of these issues should have been fixed with update 4.21.0. Please wait for it to get reviewed by browser app stores and try again later.

Also please notice that for the first issue, it's more likely that PhotoShow will not display an HD image since it doesn't know an image of better quality in this scenario. However, now you should be able to have the context menu items for them.
