### ISSUE TITLE
Issues with file naming and then saving

### ISSUE THREAD

**Issue by vertigo220** [Mr-VincentW/PhotoShow#114]
I was using this in Firefox, but it was ignoring the file naming setting and just using the pictures default name. I installed it a few weeks ago in Brave and started using it there, and in that browser it was naming correctly, but when I just tried it today, it wouldn't even download anymore. I switched back to Firefox and it still downloaded, but then I uninstalled and reinstalled it to see if that would get the naming to work right and now it won't download, either, so I'm guessing something changed in the update a few days ago that broke that. Both of these issues, in both browsers, are with any site I've tried.

**Comment by Mr-VincentW** [comment]
Thank you for your feedback. Please follow the instructions below and try again.

1. Make sure you have the latest PhotoShow installed (4.22.0 currently).
2. Make sure you have logged in to your browser account, otherwise, the settings of PhotoShow cannot be saved.
3. Please check if you have other browser extensions that manage file download as well, there might be a conflict.
4. Attach some links where you had this issue and your PhotoShow naming settings for me to test.

**Comment by vertigo220** [comment]
I had the latest installed in both browsers. As mentioned, I'd just installed it in Brave, and uninstalled and reinstalled in Firefox. The settings are saved and I checked multiple times to make sure they were set properly. Only a couple other extensions in each browser, which are both different between the browsers and don't handle downloads. When I tried again later, PhotoShow was downloading again in both browsers, and it's continued to do so, so not sure what the problem was at the time. However, there was one image/site that worked in Brave but not Firefox, but don't remember which.

Also, Firefox continues to incorrectly name the downloads. Not only does it still use the file's name instead of renaming it, but it has a weird issue with DuckDuckGo where if I have DDG as my default search engine and search for something in the address bar, it will save the images with their names and extensions (though still not using the naming scheme it's supposed to), but if I go to DDG and search from the site, then try to save images, they save as "th" with no extension.

Finally, the pop-up that says the image will be downloaded shortly doesn't show in Firefox, making it easy to miss that it was downloaded and think it wasn't (though I'm fairly certain that's not what was happening before, because I was checking the downloads folder).

Not sure if these should be separate issues or if they're related as a difference in functionality between Brave/Chrome and Firefox.

**Comment by Mr-VincentW** [comment]
1. PhotoShow did have the download feature broken since an update a couple of weeks ago. This has been addressed recently in update 4.22.1 (updated on 30 Mar). That likely is why you had the issue but could no longer replicate it.

2. Based on your description, you must have `<O>` in your download file naming pattern. Unfortunately, this doesn't actually work in Firefox as it doesn't provide an approach for extensions to get the original filename. In this case, the `<O>` pattern placeholder is instead mapped based on the image links in Firefox, which is always **"th"** for images in GGD's search results. You may give the new pattern placeholder `<I>` a go which grabs the title or description info of an image and still use the "original filename" as a fallback when this info is unavailable.

4. Since most browsers have their own download indicator, displaying another download message seems to be a bit redundant and annoying, especially when you're downloading a lot of images. PhotoShow now only displays this message if the download process can not be started within 1s. However, it has some issues which I'll be working on later.

Thanks again for all the details.

**Comment by vertigo220** [comment]
Hmm, the one in Brave is the 3/30 version, so it must have auto-updated, but the one in Firefox is still from 3/23, so no updated to the "fixed" version yet it does work, so I'm not sure that was the problem. Unfortunately, we may never know, but at least it's working now.

The \<I> instead of \<O> does seem to be working. I'll have to test on other sites as I go, but I don't see why it wouldn't work everywhere else since it's working on DDG and Google.

I still need to get Firefox set up, and part of that will be an extension to show downloads in a status bar, so that will help with the third issue. So it seems this issue is resolved. However, I'll let you close it, as I do have a suggestion pertaining to it, which is that since <O> doesn't work in Firefox, which will likely lead to people wondering why it's not working, as I did, it seems it would be better to simply remove it as an option in the Firefox version. It doesn't even necessarily need to be completely removed; just remove it from the settings pop-up so users don't see it as an option (though this could still cause issues if someone copies their config from a Chromium browser to Firefox).

**Comment by Mr-VincentW** [comment]
The `<I>` placeholder guides PhotoShow to grab the `title` or `alt` attribute of an image element on webpages, which unfortunately are not provided by all websites for all of their images, all depending on how the sites were built. DDG and Google really did a good job on this point.

People can have different interpretations of what an "original filename" is for an image on a website. In Firefox, since we cannot retrieve the actual filename that a site provides for its images when they're requested to be downloaded, PhotoShow grabs the last segment from the image URL (usually before an image format name e.g. `.jpg`/`.png`/etc.) and use it as the "original filename". This "name" may not be as descriptive as the `title` or `alt` attribute but still makes sense in terms of making a filename. So the `<O>` placeholder will be retained in Firefox and hopefully one day it will work as expected.

I'll think about the download message issue again and optimize it, thus this issue will keep open until I finish the work on this.

Thank you very much for the suggestions.

**Comment by Mr-VincentW** [comment]
The filename feature should have been improved now that if filenames are provided by the server when images are requested to be downloaded, they will be used accordingly based on your PhotoShow `File Naming` settings. Otherwise, the `<I>` placeholder will still be a good fallback. Cheers.
