### ISSUE TITLE
Request:  Change the toggle on/off just by clicking its icon

### ISSUE THREAD

**Issue by decembre** [Mr-VincentW/PhotoShow#139]
It's possible to toggle on/off just by clicking its icon (and not click to open its menu and click "disable" / "enable" to toggle it ?
And add a caret to its icon to open its menu of options.

I don't need to change its options all the time, but often toggle it for different sites...

**Comment by Mr-VincentW** [comment]
Hi, thank you for the feedback.

Unfortunately the extension icon can only do one action which means there's no way to attach an extra behavior to it.
However, you can toggle on/off for the current website you're visiting via shortcut instead of having to open the menu. Please find the shortcut settings as per the image attached below:

### **Chrome -** [chrome://extensions/shortcuts](url)
![image](https://github.com/Mr-VincentW/PhotoShow/assets/54405631/012c74bc-787f-4be7-8de7-4ae999a49205)

### **Firefox -** [about:addons](url)
![image](https://github.com/Mr-VincentW/PhotoShow/assets/54405631/3892d05a-dd27-4e3a-8f02-26bd62d2002b)

### **Microsoft Edge -** [edge://extensions/shortcuts](url)
![image](https://github.com/Mr-VincentW/PhotoShow/assets/54405631/567bdd0e-fd40-41bf-9730-dd5b71662fc2)

**Comment by decembre** [comment]
Thanks for the reply :-)
Damn Quantum:
Their API lake of many support for simple thing like that.
It was because i wanted to stay with the old Waterfox Classic,
but it became more an more difficult to use it now.

**Comment by Mr-VincentW** [comment]
Understood. For firefox, you may wanna try pinning PhotoShow or any other extension icon in the toolbar to make them easier to reach when you need to click on them.
![image](https://github.com/Mr-VincentW/PhotoShow/assets/54405631/e76031a1-23b4-4601-ad00-87213ae029e1)

**Comment by decembre** [comment]
Thank:
I do that before my request...

**Comment by decembre** [comment]
An other idea:
1 - Icon which only do only the toggle action
2 - Add an arrow near the icon which only  open the menu
It's possible ?

**Comment by Mr-VincentW** [comment]
Unfortunately not, the toolbar icon is part of the UI of the browser where extensions can do nothing but respond to clicks.
