### ISSUE TITLE
Don't inject this CSS: ::before, ::after {   pointer-events: none !important;}

### ISSUE THREAD

**Issue by decembre** [Mr-VincentW/PhotoShow#141]
This CSS interfere too many with some functions i add with some of my Userstyles.
By example when i use a ::before to open a menu.
Your pointer-events prevent it.
And i need to disable PhotoShow to be able to use my userstyle.

This selector:
 ::before, ::after, is very generic and I suppose it should break for some site which use it.

**Comment by Mr-VincentW** [comment]
Thank you for your feedback.
PhotoShow highjacked all pseudo-elements because on many sites they're used as overlays on images which block PhotoShow from interacting with the images. However, it seems that highjacking them has been creating more problems than benefits thus I decided to remove it since update 4.32.0.
In the future PhotoShow will try new approaches to interact with the images without needing to affect any original content.

**Comment by decembre** [comment]
Thanks!

**Comment by decembre** [comment]
Maybe you can drop an eye on:
 <a href="https://addons.mozilla.org/fr/firefox/addon/xifr/?utm_source=flickrhacks" rel="noreferrer nofollow">xIFr</a>
It's an exif viewer and it can find its exif without problem through any site protection.
