### ISSUE TITLE
S Hotkey and download notification pop-up stopped working

### ISSUE THREAD

**Issue by vertigo220** [Mr-VincentW/PhotoShow#15]
I don't update or restart my browsers very often, but my computer randomly shut down last night, and now the save hotkey for this isn't working. The only thing I can figure is something in one of the recent Firefox updates (now on 85.0.2, was probably on 85.0 before) broke it. The image pop-ups show, I can right-click and use the PhotoShow context menu entry to save the HD image, I just can't trigger it with the s key. Also, it no longer shows the pop-up saying the image is being downloaded. The only thing that happens now is the browser download arrow briefly changes, which isn't nearly as noticeable. It's the same on multiple sites, including Google Images.

**Comment by Mr-VincentW** [comment]
Thank you for your feedback. I checked on my Firefox (both on 85.0 and 85.0.2 after upgrading) on Google Images. PhotoShow works normally as well as the `S` hotkey action. 

So it could potentially be a tough problem if it still wouldn't work properly at yours. You may send me another email via the ✉ icon on PhotoShow's popup window while visiting the website, through which approach the email will automatically contain the basic environmental information that might be helpful for debugging.

You can also try to reinstall PhotoShow to see if it makes any sense.

I'll keep this issue open until getting your feedback or a fortnight later.

**Comment by vertigo220** [comment]
Uninstalling and reinstalling the addon (restarted Firefox in between) had no effect. And email option doesn't work, since it just opens whatever email client is set up as default, but I don't have any clients configured, since I just use webmail. There should be a button to just copy the info to the clipboard. Anything else I can do to help figure this out?

**Comment by vertigo220** [comment]
I figured out the issue. I realized no hotkeys were working, and tried to think what might be blocking input, then realized what it was. My computer restarted on me the other night, which is why Firefox updated (and why I thought that was the problem), and one thing that resulted from that was Ghostpress, an anti-keylogger, ran at startup. It wasn't running before, which is why PhotoShow worked before, but it blocks or scrambles the key input and PhotoShow isn't receiving it. It's odd because I can obviously type in the browser, and all other applications for that matter, so the input is received perfectly fine by it, just not by PhotoShow. I tried another addon that uses hotkeys (https://addons.mozilla.org/en-US/firefox/addon/suprhotkeys/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) and it works fine, so it seems this isn't an issue with addons not receiving the keys properly, but with PhotoShow specifically (though of course there may be others, but the point is it doesn't seem to be due to a limitation). So I wonder if it's something that can be fixed so it will work. It's not a big deal, and certainly not a priority, since now I know what the problem is and at the very least maybe it could warn users that anti-keyloggers may interfere, to keep them from spending time troubleshooting, but it would be nice if you could get it to work.

**Comment by Mr-VincentW** [comment]
Thanks again for the details. I was thinking that it looked like the communication between the page and the extension background code was blocked or somehow didn't work properly, since saving images and some other stuff rely on it. You can figure it out simply by testing whether hotkeys like `Esc` (closing image preview popup) or `Shift` + `Ctrl` + `Left` / `Right` arrow keys (rotating image) work as these actions don't require extension communications at all. Is there any possibility that you have got some other security guarding extensions or software or even a setting item in the browser itself that might potentially block extension messaging?

If the above doesn't help much, you can still try inspecting the running state of PhotoShow by checking its console for the background code while triggering these broken hotkeys. Please follow these steps:

1. Open the Toolbox window by clicking the `Inspect` button on [this page](about:debugging#/runtime/this-firefox). You might need to drag and open it in a separate window.
![image](https://user-images.githubusercontent.com/54405631/108122743-a01f9200-7109-11eb-8193-6f2e00dc6e01.png)

2. Try PhotoShow's hotkeys for saving images or something else on another page like Google Images and check the output in the inspector console to see if there are any error messages.
![image](https://user-images.githubusercontent.com/54405631/108123075-2d62e680-710a-11eb-961b-50a860264385.png)

Thanks.

**Comment by vertigo220** [comment]
Esc and rotation do work. No other addons. Not likely to be a browser setting since it's set the same as it was before, and it works when I disable Ghostpress, which is also why it's unlikely related to any other software. Not sure what you were suggesting with point 1 (the first image), but I opened the console and tried saving an image and nothing happened, no console output. Strangely, though, it started working, even with Ghostpress active, but then a few minutes later I tried again and it wasn't working again. Not sure if that was due to a failure of Ghostpress or what. I tried to replicate it but on luck.

**Comment by Mr-VincentW** [comment]
Sorry, there supposed to be a link on "**this page**", no idea where it went, probably got banned by GitHub? Anyway I'm gonna list it here: [about:debugging#/runtime/this-firefox](about:debugging#/runtime/this-firefox). Open this link in your Firefox and hopefully you will see what I showed in the first pic.

**Comment by vertigo220** [comment]
Still no output/errors. Opened the inspector on console tab, switched to Google Images, tried saving an image with S key, checked the console and nothing.

**Comment by Mr-VincentW** [comment]
Oh, such a pain! There's nothing more I can do right now. Maybe I'll give it a go with installing Ghostpress sometime later. 😓 Sorry about the problem and thanks again for the feedback and all your efforts in helping to debug.

**Comment by vertigo220** [comment]
No worries. Like I said, it's not a huge deal and certainly not a priority, and even if you can't/don't fix it PhotoShow is still great and I wouldn't blame you, just thought you might want to try. Let me know if I can do anything more to help.

**Comment by Mr-VincentW** [comment]
Cheers! Will let you know should there be any progress on it.

**Comment by Mr-VincentW** [comment]
I ended up installing Ghostpress, testing it with PhotoShow and yes, it is Ghostpress that has been blocking the keyboard events on a low-level so PhotoShow can only get tampered hotkey events when Ghostpress is running. Luckily, there is a way to work around and it'll get fixed with the next update of PhotoShow.

**Comment by vertigo220** [comment]
Cool. I actually discovered yesterday (meant to mention it sooner but got busy and forgot) that it also blocks input to PotPlayer, so I'm probably going to uninstall it anyway. Still good to fix it, though, just in case other users happen to be running it or possibly a different anti-keylogger.

**Comment by Mr-VincentW** [comment]
This problem now has been fixed since version 4.6.2.0.
