### ISSUE TITLE
Size limiter! Don't enhance big pics!

### ISSUE THREAD

**Issue by im3or** [Mr-VincentW/PhotoShow#17]
Can there be a size limit in what gets enhanced. I mean if the image is already 800x600 there is no need (for me at least) to show it in bigger size, which in turn actually puts it in a smaller window. I mean if i want, i can always view it in panorama mode but i only want smaller size images to get bigger.

**Comment by Mr-VincentW** [comment]
Thanks for your feedback. Normally PhotoShow doesn't work on pics that are not thumbnails - being of large sizes. However, as this is not programmatically detected currently, there might be some cases where large pics are also treated equally. Would you mind attaching some specific bad cases (links) so that I can have an inspection? Would appreciate it.

**Comment by im3or** [comment]
![Untitled](https://user-images.githubusercontent.com/30718972/115486744-e792dd80-a274-11eb-9d26-c6fde1a8c648.jpg)

Here is an example, image is already big for me to see, but it enhances it anyway with a drag zoom, i don't want this.
If it is possible to add size limiter or minimum size to zoom then please add this customization.

**Comment by Mr-VincentW** [comment]
Good idea! Gonna add it in future versions and will let you know then. Thanks.

**Comment by Mr-VincentW** [comment]
Hi there, PhotoShow has added a new feature since version 4.7.0.0 that when thumbnails are larger than 25% of the viewport (by area), the HD image viewer will not popup by default. You can change this behaviour in PhotoShow's setting window. For some cases, the HD viewer can still be smaller than the thumbnail itself, but it's much rarer. I'll close this issue for now. If you have more ideas about it, you can reopen it. Thank you.
