### ISSUE TITLE
Keyboard shortcuts stopped working since latest update

### ISSUE THREAD

**Issue by garyking** [Mr-VincentW/PhotoShow#181]
It looks like keyboard shortcuts have stopped working since the latest update. For instance, hovering over an image and making the zoomed in image appear by holding Option on Mac still shows the full image, but then letting go of the Option key and pressing Tab no longer opens the image in a new tab, despite it working before.

**Comment by Mr-VincentW** [comment]
Hi, thank you for your feedback!

This issue has been fixed in a recent update, which is currently under review by the Chrome Web Store. Once the review process is complete, your browser should automatically update to the latest version. Feel free to reopen this issue if the problem continues then.

Cheers.
