### ISSUE TITLE
URLs of HD images are changed for the worse in Firefox

### ISSUE THREAD

**Issue by antonot** [Mr-VincentW/PhotoShow#182]
When I open HD image in a new tab, in Firefox the URL of the image now looks like blob:moz-extension://[here is a set of letters and numbers]. In this format it cannot be opened when I send this URL to anybody through a messenger. At the same time, in Chrome the URL still looks properly.

Let's take this article as an example: https://www.bbc.com/travel/article/20241016-kamikochi-japans-car-free-town-that-autumn-hikers-love.

The URL of the title photo, if you try to open the HD image in a new tab, in Firefox looks like this:

blob:moz-extension://d79fe348-751f-4671-9cac-5a31d50761ed/171a8bb1-ba30-4ae6-a5d0-4d699a03ef82

And in Chrome it's like this: https://ichef.bbci.co.uk/images/ic/1920xn/p0jy1w4y.jpg.webp

As far as I could see, the URL change in Firefox is very recent, and I don't think it did any good. :-(

**Comment by Mr-VincentW** [comment]
Hi Anton,

Thank you for your feedback!

The change you noticed was introduced in update 4.6.0, which is still under review for Chrome users. That’s why you’re seeing different behavior.

The blob-prefixed URLs only exist temporarily in your browser’s memory, so they can’t be shared. Once the tab is closed, the URL is no longer valid. This update was made to enhance the experience for the following reasons:
- To prevent certain images from automatically downloading when opened in a new tab on some sites.
- To allow data URLs to open in a new tab, a feature that isn’t typically available in Firefox.

For your particular needs, you can still access the actual URL of large images in two ways:
- Press the `C` hotkey when hovering over a thumbnail, whether the large image viewer is shown or not.
- Use the `Copy HD Image Address` context menu option, as shown in the screenshot below:
  ![image](https://github.com/user-attachments/assets/f1b9bc99-e40b-476d-8498-eaaf799ff65c)

Both methods will copy the HD image address to your clipboard.

I'll review the change regarding the URL in the new tab to see if it’s worth rolling back. In the meantime, if you have any other reasons why this is necessary, please feel free to share them.

Thanks again!

**Comment by antonot** [comment]
Hi Vincent, thank you for your quick reply!

Actually PhotoShow is just a great addon that I can't imagine using Firefox comfortably without anymore, and thank you so much for it!

I still don't understand the higher meaning of switching to blob-prefixed URLs, but I don't ask you to explain it to me again — you are the developer and you know why you did it.

I'd just like to add that with the introduction of blob-prefixed URLs, opening HD image in a new tab for Instagram.com now doesn't work — for absolutely all posts in my feed. Instead of HD image, the new tab opens just blank. :-)

**Comment by Mr-VincentW** [comment]
Hi Anton,

I'm glad to hear PhotoShow has been useful for you!

Although I haven’t encountered any issues opening images in a new tab on Instagram in Firefox, I’ve decided to restore the URL behavior to its original state while looking for another workaround to address the issues this change was meant to fix.

I'll reopen this issue and keep it open until the updates are completed. Thanks!

**Comment by gluid** [comment]
Hello again.
I too want to add that with the latest update, TAB opens all images with blob prefix, which doesn't allow you to quickly save the image with Ctrl+S combination (atleast on Chrome), moreover it doesn't keep the original filename that way.

I also would like to suggest for extension's S hotkey to save the image in the last saved destination instead of browser's default destination, or atleast make that an option.
for example, browser's default folder is /Downloads, but last saved folder is /Downloads/Images
pressing S would save in /Downloads instead of /Downloads/Images

and also maybe add Alt or Shift key to that hotkey to open dialogue window to change the save location and the filename.
right now, "Always ask before downloading" checkbox jumps me back to default folder and it's really annoying.

**Comment by Mr-VincentW** [comment]
Hi gluid,

The issue of not being able to save images using `Ctrl + S` for blob-prefixed URLs wasn’t expected, especially since the save option in the context menu still works for those URLs. Thank you for bringing this to my attention. I apologize for the inconvenience, and I’ll be rolling back the URL changes in the next PhotoShow update.

Due to security and privacy concerns, browser extensions don’t have access to the last folder or location where files are downloaded, nor can they save files outside of the default download folder. However, you can specify a subfolder in PhotoShow’s settings. For example, with the settings shown in the screenshot below, images will be downloaded to `<Default-Download-Folder>/PhotoShowDownloads/` using the "original" filename obtained from the server response or the image url. This setting also works when "Always ask before downloading" is ticked, as it automatically fills in the download prompt.
![image](https://github.com/user-attachments/assets/4605c32c-d0ba-463e-8fab-7762d33dacbd)

Currently, no assistant key (Alt, Ctrl, or Shift) is used due to potential conflicts with the key that activates the viewer. However, future versions of PhotoShow may introduce custom hotkey options for more flexibility.

Cheers.

**Comment by gluid** [comment]
I see, thank you for the explanation, that helps.
I will be waiting for the update, I appreciate your hard work.

**Comment by antonot** [comment]
Sorry to bother you again, but I seem to have found another bug, and it seems to be in the latest version, so I'll describe it here (but if you say I need to open a separate issue for each bug, no problem).

When the C hotkey (Copy HD Image Address) is enabled, the ability to copy selected text using the Cmd+C hotkeys in Firefox on MacOS disappears. When "C" is unchecked in the PhotoShow settings, the hotkeys for copying selected text work again. I only noticed this last week.

I've never used the hotkey to copy the address of an HD image, so turning it off is not a problem for me, but it seems (although I'm not sure) to have always been on by default, and the conflict with Cmd+C has only recently arisen.

**Comment by Mr-VincentW** [comment]
No need to worry about opening another issue, I can follow that here. Also thanks for reporting bugs again 🙂.

Yeah this is exactly a new bug introduced with last update. It'll be addressed with the next release too.
You'll be updated soon. Thank you!

P.S. PhotoShow settings should persist through updates. So, if you’ve turned off a hotkey, it shouldn’t automatically turn back on. If it's behaving differently, feel free to let me know.

**Comment by Mr-VincentW** [comment]
Hi everyone,

Just letting you know that all the issues mentioned above have been addressed in update 4.47.0. For browsers other than Firefox, this update is still under review.

I’ll close the issue for now. If the problem persists in the new version, please feel free to reopen it. Thank you!
