### ISSUE TITLE
Add Option to disable some hotkeys

### ISSUE THREAD

**Issue by fookbuck** [Mr-VincentW/PhotoShow#2]
I just notice new hotkeys like (s / c) and customize hotkeys its not available right now.
I want to disable them instead. 
because Im not intend to download / copy them sometime on chat.

**Comment by Mr-VincentW** [comment]
Thank you for your feedback.

I've updated PhotoShow to version 4.2 since which the hotkey actions have been optimized for better user inputting experience. Now when you are typing, most PhotoShow hotkeys will not work. What's more, I've also added toggles for all hotkeys, they can be disabled thoroughly now. This is a temporary solution as PhotoShow is planing to support hotkeys customization in the future.

You might need to wait for usually a week or so until Google Webstore or Microsoft Store complete reviewing the new version. If you're a Firefox user, the new version is already online.

Kind regards.

**Comment by fookbuck** [comment]
Thank you for update.

I tried version 4.2, It's working better than previous version but it still try to download / copy if I double tap on hotkeys. 
But nevermind, I can disable them now.

**Comment by Mr-VincentW** [comment]
Thank you for your supplementary.

PhotoShow only activates its hotkey actions when you hover your mouse on an image thumbnail and the currently focused element on the page is not an input element (text box, button, etc.). As such, when you are typing to input something, the hotkey actions will not work even your mouse is hovering on an image.

So, I wonder what's the specific use case that you were in. In what cases you need to type in something (or "double tap or spam on hotkeys") in an input element while hovering your mouse on an image. If you were tapping hotkeys while not being inputting, then the behavior is expected. 

If you don't mind, you may attach the link of the page and describe how I can repeat the problem you encountered. Sometimes it might just due to some code conflict with the origin page.

Thank you for helping PhotoShow become better.

**Comment by fookbuck** [comment]
In my case, I was typing chat on facebook but my mouse is hovering on image and this extension will try to copy link / download image if I "double tap or spam on hotkeys" like I said before.

https://www.facebook.com/messages/
![image](https://user-images.githubusercontent.com/26791163/77286195-13f8c500-6d16-11ea-9b0a-84d45c653578.png)

**Comment by Mr-VincentW** [comment]
I've just fixed the problem in PhotoShow's new version 4.2.1. It was due to my neglect of a certain type of elements for inputting. You may have a try again. Thank you for your patience.
