### ISSUE TITLE
Checkbox mark stops working when addon enabled

### ISSUE THREAD

**Issue by Kyogre** [Mr-VincentW/PhotoShow#78]
When PhotoShow is enabled on one of my pages checkbox marks stop working.
Workaround: disable addon for webpage.

I attached video demo and page example used in the video:
[page with checkbox example.zip](https://github.com/Mr-VincentW/PhotoShow/files/10199542/page.with.checkbox.example.zip)
https://user-images.githubusercontent.com/2260980/206841532-ef817b73-db01-457c-b367-d94476d5cadf.mp4

**Comment by Mr-VincentW** [comment]
Hi Roman,

Thanks for reaching out to me with the feedback. I checked your video and the page example attached. Here're the problem reason and potential solutions.

CAUSE:
1. PhotoShow currently sets "pointer-events: none" style to all :before and :after pseudo elements. This is because a lot of websites use pseudo elements as image masks which block PhotoShow from picking up images. Given that in most cases, pseudo elements only affects visual styles instead of interactions, PhotoShow set this style on all websites where it's enabled by default.

2. These checkboxes on your website are built with absolutely-positioned pseudo elements hence the wrapper label elements don't have valid sizes, which is why they can't take mouse interactions.

SOLUTIONS:
1. You may send me the origin (domain) of your website and I can add a specific rule to PhotoShow to allow these pseudo elements to behave normally.

2. You may tweak the implementation of your website a bit and make the wrapper label elements working even when the inner pseudo elements have "pointer-events: none" style.

Let me know if you have further concerns. Thanks.

Kind regards,
Vincent
On 10/12/2022 9:40:48 pm, Roman Отряскин ***@***.***> wrote:
When PhotoShow is enabled on one of my pages checkbox marks stop working.
Workaround: disable addon for webpage.
I attached video demo and page example used in the video:
page with checkbox example.zip [https://github.com/Mr-VincentW/PhotoShow/files/10199542/page.with.checkbox.example.zip]
https://user-images.githubusercontent.com/2260980/206841532-ef817b73-db01-457c-b367-d94476d5cadf.mp4 [https://user-images.githubusercontent.com/2260980/206841532-ef817b73-db01-457c-b367-d94476d5cadf.mp4]

**Comment by Kyogre** [comment]
ok, and thanks for the answer! I have heard you.
Because our company have many such websites (some of them even hosted only in our local network), I have only second solution available for us.
You can close this thread if you need.
