### ISSUE TITLE
Don't show

### ISSUE THREAD

**Issue by davidp88** [Mr-VincentW/PhotoShow#88]
Don't show -- hd image download will start soon.

**Comment by Mr-VincentW** [comment]
Thank you for your feedback. It'd be more helpful and appreciated if you could attach some links where the problem happened, as well as some brief description about how to replicate it. Cheers.

**Comment by davidp88** [comment]
The above message is shown in ff when one presses "S" to save the image(shown in all sites supported),no more info I can give to replicate it.

**Comment by Mr-VincentW** [comment]
So you prefer to download images without seeing the popup messages - is this what you mean?

**Comment by davidp88** [comment]
yes

**Comment by Mr-VincentW** [comment]
I'll see what I can do with it.

**Comment by davidp88** [comment]
sir,as one can see the download of the image by the animation in ff,not necessary

**Comment by Mr-VincentW** [comment]
PhotoShow displays this message because not all image download processes can start immediately. For some images on some websites, this process takes some extra time after you press down the "S" key or click in the context menu, in which case if users are not given any perceivable idea of the download, they might think it hasn't been triggered thus will try again, which will lead to multiple downloads.

I'll think about this again later, chances are that I might add a new toggle button to allow you to turn off all messages.

**Comment by Mr-VincentW** [comment]
A new release 4.20.0 has been published with which the download messages only display when the download processes can not start within 1s. Thanks.
