### ISSUE TITLE
Videos on Facebook don't play the last days.

### ISSUE THREAD

**Issue by Crackz11** [Mr-VincentW/PhotoShow#94]
Videos on Facebook don't play. They look like still images. If I disable photoshow videos work again. :/

**Comment by Mr-VincentW** [comment]
Thank you for your feedback, please attach a link to the page where this happened as well as some guidelines for how I can replicate this issue. Thanks.

**Comment by antarn88** [comment]
I have the same problem, with Google Chrome v110 - on Windows 11.

I log into Facebook, go to the news feed, scroll down, and all the videos show the same phenomenon. The videos are treated as images.

It won't start the video, if I press a right button, it offers to "Save Image" etc.

Also, there are problems with Facebook Stories. The entire left sidebar is broken. It is not clickable or scrollable. And story images don't enlarge either.

And finally, there are a few small bugs I'd like to mention:

In the newsfeed, any post with the X hiding icon is also zoomed out, which I think is unnecessary. Same thing with the tiny icons next to the "Write a comment" input field, also on any post.

**Comment by Mr-VincentW** [comment]
Please attach some links and screenshots which will help me allocate the issues since I cannot replicate them on my FB.

PhotoShow cannot preview videos at the moment, video covers will be displayed instead.

My FB sidebar works well. Please provide more detail about this issue on yours.

Currently, PhotoShow tries to provide previews for all kinds of images on a webpage, including those ones that are used as button icons or decorative purposes. However, this will be addressed in the future when I'll try to figure out a way to filter out these items.

**Comment by antarn88** [comment]
I have attached some pictures when I experience the issues.

![facebook stories](https://user-images.githubusercontent.com/61657422/218306995-9571d831-ca0a-4baf-8526-d9041cc7d2b8.png)
![video1](https://user-images.githubusercontent.com/61657422/218306996-5b4db904-81b6-4c82-8d90-93caec890b12.png)
![video2](https://user-images.githubusercontent.com/61657422/218306999-45d2ba93-fb8f-4fa9-91ba-7c8cc7204490.png)

And some video links:
https://www.facebook.com/andras.novak.16/posts/pfbid0eUpPqefH45xsnWBnvzFXP3yUmhhQv6r8H68kz3jxaaw2Ep6St8suLktSjwLjDDHvl
    https://www.facebook.com/ferenc.kiss.524/posts/pfbid02G1B8PwrHqRsyp47kcfUXwHvipk7o2wqJi5z8P3aiLKvEmsidBQ4KYShtxeHB6WcXl
    https://www.facebook.com/yturnquest/posts/pfbid0k9RxhUf8XC2ieqMFqeuVFm6qV75vFCJSiPvkFmo9tu8eDWxhPEwNGSx4pVtSMzKel

**Comment by Mr-VincentW** [comment]
Thanks again for your feedback. This issue has been fixed in update 4.20.1.

**Comment by antarn88** [comment]
Thanks for the fix.
However, another bug has been generated here:
In Facebook Stories, when I open the stories, the stories are now clickable, but scrolling is not possible, and the scrollbar does not work.

Also, when I open a picture anywhere on Facebook, it is totally broken. Enlarging does not work, and the context menu does not have the options for the image. To try it out, click on any large image.

Maybe one more little bug.
I cannot click on videos with the Play icon, only when I click on other areas of the video. But otherwise it works fine, that's all.

**Comment by Mr-VincentW** [comment]
Can you please attach more details on the scrolling issue? Sorry I'm not a regular FB user and could not find on which part of a page this issue happens.

**Comment by antarn88** [comment]
Of course.
I attached a screenshot.
![stories](https://user-images.githubusercontent.com/61657422/220046317-a79247ea-d211-4d82-8298-eae78c7db05a.png)
